#define NETWORKSSID "<SSID>"
#define PASSWORD "<PASSWORD>"

#define SENSORNAME "<PASSWORD>"
#define INFLUXDBADRESS "influxdb.example.com"
#define INFLUXDBNAME "<PASSWORD>"
#define INFLUXUSERNAME "<USERNAME>"
#define INFLUXDBPASSWORD "<PASSWORD>"
