#define NETWORKSSID "<SSID>"
#define PASSWORD "<PASSWORD>"

#define SOFTWARE_VERSION "v1.0_2021-01-01"
#define SENSORNAME "<PASSWORD>"
#define INFLUXDBADRESS "influxdb.example.com"
#define INFLUXDBNAME "<PASSWORD>"
#define INFLUXUSERNAME "<USERNAME>"
#define INFLUXDBPASSWORD "<PASSWORD>"
